import Head from 'next/head'
import React from 'react'
import Login from '../pages/login'
import { useAuth } from '../utils/AuthContext'
import SideBar from './SideBar'


const Layout = ({ children }) => {
    const { currentUser, loading } = useAuth()
    return (

        <>
            <Head>
                <title>Gestion de cotes Malkia</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            {
                loading && <div>Loading ...</div>
            }
            {
                currentUser ? <div className='w-screen flex h-screen bg-slate-200'>
                    <SideBar />

                    <div className='flex-grow overflow-y-auto'>
                        <div className=''>{children}</div>
                    </div>
                </div> : <Login />

            }
        </>

    )
}

export default Layout